#!/usr/bin/env bash
set -euo pipefail

OUTPUT="${1:-/etc/nginx/cloudflare-realip.conf}"
RELOAD_NGINX="${RELOAD_NGINX:-0}"
DRY_RUN="${DRY_RUN:-0}"
OFFLINE="${OFFLINE:-0}"

if [[ "${DRY_RUN}" != "1" && "${EUID}" -ne 0 ]]; then
	echo "Run as root: sudo $0 ${OUTPUT}" >&2
	exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

if [[ "${DRY_RUN}" == "1" && "${OFFLINE}" == "1" ]]; then
	{
		echo "# Offline dry-run placeholder. Production setup fetches Cloudflare IP ranges."
		echo "real_ip_header CF-Connecting-IP;"
		echo "real_ip_recursive on;"
	} > "${tmp}"
else
	if ! command -v curl >/dev/null 2>&1; then
		echo "curl is required to fetch Cloudflare IP ranges." >&2
		exit 1
	fi

	{
		echo "# Generated by portfolio refresh-cloudflare-real-ip.sh"
		echo "# Source: https://www.cloudflare.com/ips/"
		curl -fsSL https://www.cloudflare.com/ips-v4 | while IFS= read -r cidr; do
			[[ -n "${cidr}" ]] && printf 'set_real_ip_from %s;\n' "${cidr}"
		done
		curl -fsSL https://www.cloudflare.com/ips-v6 | while IFS= read -r cidr; do
			[[ -n "${cidr}" ]] && printf 'set_real_ip_from %s;\n' "${cidr}"
		done
		echo "real_ip_header CF-Connecting-IP;"
		echo "real_ip_recursive on;"
	} > "${tmp}"
fi

if [[ "${DRY_RUN}" == "1" ]]; then
	cat "${tmp}"
	exit 0
fi

install -m 0644 "${tmp}" "${OUTPUT}"

if command -v nginx >/dev/null 2>&1; then
	nginx -t
	if [[ "${RELOAD_NGINX}" == "1" ]]; then
		systemctl reload nginx
	fi
fi

echo "Wrote ${OUTPUT}"
